---
apiVersion: karpenter.k8s.aws/v1beta1
kind: EC2NodeClass
metadata:
  name: custom-1a
spec:
  amiFamily: AL2
  role: "KarpenterNodeRole-testnet" 
  subnetSelectorTerms:
    - tags:
        karpenter.sh/discovery: testnet
        Name: node1a
  securityGroupSelectorTerms:
    - tags:
        karpenter.sh/discovery: testnet
  amiSelectorTerms:
    - name: "amazon-eks-node-1.29-*" 

---
apiVersion: karpenter.k8s.aws/v1beta1
kind: EC2NodeClass
metadata:
  name: custom-1b
spec:
  amiFamily: AL2
  role: "KarpenterNodeRole-testnet" 
  subnetSelectorTerms:
    - tags:
        karpenter.sh/discovery: testnet
        Name: node1b
  securityGroupSelectorTerms:
    - tags:
        karpenter.sh/discovery: testnet
  amiSelectorTerms:
    - name: "amazon-eks-node-1.29-*" 

---
apiVersion: karpenter.k8s.aws/v1beta1
kind: EC2NodeClass
metadata:
  name: custom-1c
spec:
  amiFamily: AL2
  role: "KarpenterNodeRole-testnet" 
  subnetSelectorTerms:
    - tags:
        karpenter.sh/discovery: testnet
        Name: node1c
  securityGroupSelectorTerms:
    - tags:
        karpenter.sh/discovery: testnet
  amiSelectorTerms:
    - name: "amazon-eks-node-1.29-*" 
