---
apiVersion: karpenter.sh/v1beta1
kind: NodePool
metadata:
  name: custom-1a
spec:
  template:
    metadata:
      labels:
        type: karpenter
        azsubnet: custom-1a
      annotations:
        k8s.amazonaws.com/eniConfig: custom-ap-southeast-1a
    spec:
      requirements:
        - key: "karpenter.k8s.aws/instance-category"
          operator: In
          values: ["m", "r"]
        - key: "karpenter.k8s.aws/instance-cpu"
          operator: In
          values: ["2", "4"]
        - key: "karpenter.k8s.aws/instance-hypervisor"
          operator: In
          values: ["nitro"]
        - key: "karpenter.k8s.aws/instance-generation"
          operator: Gt
          values: ["5"]
        - key: "topology.kubernetes.io/zone"
          operator: In
          values: ["ap-southeast-1a"]
        - key: "kubernetes.io/arch"
          operator: In
          values: ["amd64"]
        - key: "karpenter.sh/capacity-type"
          operator: In
          values: ["on-demand"]
      nodeClassRef:
        apiVersion: karpenter.k8s.aws/v1beta1
        kind: EC2NodeClass
        name: custom-1a
  limits:
    cpu: 1000
  disruption:
    consolidationPolicy: WhenEmpty
    expireAfter: 720h 
    consolidateAfter: 30s

---
apiVersion: karpenter.sh/v1beta1
kind: NodePool
metadata:
  name: custom-1b
spec:
  template:
    metadata:
      labels:
        type: karpenter
        azsubnet: custom-1b
      annotations:
        k8s.amazonaws.com/eniConfig: custom-ap-southeast-1b
    spec:
      requirements:
        - key: "karpenter.k8s.aws/instance-category"
          operator: In
          values: ["m", "r"]
        - key: "karpenter.k8s.aws/instance-cpu"
          operator: In
          values: ["2", "4"]
        - key: "karpenter.k8s.aws/instance-hypervisor"
          operator: In
          values: ["nitro"]
        - key: "karpenter.k8s.aws/instance-generation"
          operator: Gt
          values: ["5"]
        - key: "topology.kubernetes.io/zone"
          operator: In
          values: ["ap-southeast-1b"]
        - key: "kubernetes.io/arch"
          operator: In
          values: ["amd64"]
        - key: "karpenter.sh/capacity-type"
          operator: In
          values: ["on-demand"]
      nodeClassRef:
        apiVersion: karpenter.k8s.aws/v1beta1
        kind: EC2NodeClass
        name: custom-1b
  limits:
    cpu: 1000
  disruption:
    consolidationPolicy: WhenEmpty
    expireAfter: 720h 
    consolidateAfter: 30s

---
apiVersion: karpenter.sh/v1beta1
kind: NodePool
metadata:
  name: custom-1c
spec:
  template:
    metadata:
      labels:
        type: karpenter
        azsubnet: custom-1c
      annotations:
        k8s.amazonaws.com/eniConfig: custom-ap-southeast-1c
    spec:
      requirements:
        - key: "karpenter.k8s.aws/instance-category"
          operator: In
          values: ["m", "r"]
        - key: "karpenter.k8s.aws/instance-cpu"
          operator: In
          values: ["2", "4"]
        - key: "karpenter.k8s.aws/instance-hypervisor"
          operator: In
          values: ["nitro"]
        - key: "karpenter.k8s.aws/instance-generation"
          operator: Gt
          values: ["5"]
        - key: "topology.kubernetes.io/zone"
          operator: In
          values: ["ap-southeast-1c"]
        - key: "kubernetes.io/arch"
          operator: In
          values: ["amd64"]
        - key: "karpenter.sh/capacity-type"
          operator: In
          values: ["on-demand"]
      nodeClassRef:
        apiVersion: karpenter.k8s.aws/v1beta1
        kind: EC2NodeClass
        name: custom-1c
  limits:
    cpu: 1000
  disruption:
    consolidationPolicy: WhenEmpty
    expireAfter: 720h 
    consolidateAfter: 30s
