apiVersion: karpenter.k8s.aws/v1beta1
kind: EC2NodeClass
metadata:
  name: default
spec:
  amiFamily: AL2
  role: "KarpenterNodeRole-testnet" 
  subnetSelectorTerms:
    - tags:
        karpenter.sh/discovery: testnet
  securityGroupSelectorTerms:
    - tags:
        karpenter.sh/discovery: testnet
  amiSelectorTerms:
    - name: "amazon-eks-node-1.29-*" 