
---
apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: default
  name: deployment-2048-1a
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: app-2048-1a
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  replicas: 30
  template:
    metadata:
      labels:
        app.kubernetes.io/name: app-2048-1a
    spec:
      containers:
      - image: public.ecr.aws/l6m2t8p7/docker-2048:latest
        imagePullPolicy: Always
        name: app-2048-1a
        ports:
        - containerPort: 80
        resources:
          requests:
            cpu: 500m
          limits:
            cpu: 1
      nodeSelector:
        azsubnet: custom-1a

